version: "3"
services:
  web:
    stdin_open: true
    # necessary for react scripts
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - /app/node_modules
      # dont map node modules inside the container.
      - .:/app
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
